version: "3.9"

services:
  livekit-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livekit-voice-ai
    ports:
      - "8081:8081"  
    env_file:
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
    user: "10001:10001"
    restart: unless-stopped
    # volumes: 
    #   - ./data:/home/appuser/data
    # healthcheck:  
    #   test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
